name: UncrafterRedux
version: 0.0.1
author: Latch
main: Latch.UncrafterRedux.UncrafterRedux
api-version: 1.16
softdepend: [Vault]
commands:
  uncraft:
    description: Uncraft
    usage: /uncraft
    permission: ur.command.uncraft
  description: Unenchant
    usage: /unenchant
    permission: ur.command.unenchant